### PR TITLE
Add initial sample data

### PR DESCRIPTION
**Pull request by bruno-pannunzio**
This PR proposes the addition of three datasets to be used as sample data:
- [Convallaria FLIM image (with calibration) in FBD format](https://zenodo.org/records/14026720) 
- [FLUTE's Embryo FLIM dataset in TIFF format](https://zenodo.org/records/8046636)
- Paramecium Hyperspectral Image in LSM format, part of [PhasorPy's test files](https://zenodo.org/records/8417894)

This enhancement is suggested in #3

### CODE REVIEW

**Comment by zoccoler** [comment]
Hi @bruno-pannunzio ,

Just a quick question about the calibration files, since I am acquiring some. I tried to make the phasor plot of the calibration file just to see how it would look like. I was expecting a single cluster somehow on top of the universal semi-circle. But I always get it outside (like below). I tested this with the fluorescein-embryo from FLUTE as well (which is the first image below). Is this to be expected? 

image

image

**Comment by bruno-pannunzio** [comment]
@zoccoler If you want you can calibrate the calibration file and you will see that it will be located in the semicircle, ay least the center of the cluster will. You can apply a median filter to reduce spread

**Comment by zoccoler** [comment]
Alright, thanks! I just wanted to ask because I saw the same plot in proprietary software, and there the cluster was already placed on top of the semi-circle (probably because the software already does some sort of auto-calibration).

**Comment by zoccoler** [comment]
I tested and it seems to be working! Thank you @bruno-pannunzio ! I am merging it.

**Pull request merged**
