### PR TITLE
Automated tests

### PR DESCRIPTION
**Pull request by zoccoler**
Hi @bruno-pannunzio @schutyb ,

I am adding automated tests as a github action to our repository. So that we can automatically check if tests are passing and our code coverage.

I would like to merge this PR before others to check if these modifications will properly trigger the github actions. For example, because phasorpy is not released yet, but we have it as a dependency, I tried to add the repository as a dependency [here](https://github.com/napari-phasors/napari-phasors/blob/7ac53d3f808907c3d1aae4ca0325664ba2fa7b59/setup.cfg#L38), but I am not sure if I did this correctly or if it works at all.

Could one of you review and potentially merge this? The changes here should not affect the plugin itself.

I also took the liberty to include all our names as authors, if that's OK with you.

Best,
Marcelo

### CODE REVIEW

**Comment by zoccoler** [comment]
Hmm I tested on my fork and it seems it the phasorpy dependency as a repo, at least the way I wrote it, does not work.
```
setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
    git+https://github.com/phasorpy/phasorpy.git@main#egg=phasorpy
```

We may need to keep testing locally if we don't find a solution to this.

**Comment by zoccoler** [comment]
Just tried something else, it doesn't work either 😅

**Comment by bruno-pannunzio** [comment]
Hi @zoccoler! I also think is a good idea to have this working before merging the other open PR's. Were you able to make it work?

**Comment by zoccoler** [comment]
Unfortunately not, I have never done this with a package that was not released.

Although important, I think we shouldn't invest too much time on this. Let's make sure the one who sends a PR writes some tests and both the one sending the PR and the one reviewing it run tests locally with `pytest`.

**Pull request closed without merging**
